### ISSUE TITLE
Medianen

### ISSUE THREAD

**Issue by johanjames** [Perham94/Temp-Converter#5]
Jag tror inte metoden Calculate i MedianTemp räknar ut medianen korrekt. Som jag förstår det måste man först sortera värdena från högt till lågt och sen plocka ut det mittersta värdet. Och om det är ett jämnt antal värden så tar man medelvärdet av de två mittersta. Jag har gjort en komplettering i MedianTemp med en ny metod getMedian() i min JavaFX.. branch. Och även en ny klass för sortering av mätvärden. Kanske inte den snyggaste lösningen men den funkar. / JOhan

**Comment by Xarczuz** [comment]
Sant måste först sortera listan sen plocka ut medianen.
